/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package hello_10

import com.mine.hello._

object Hello {
    def main(args: Array[String]) {
        val x = Utils.sum(2, 3)
        println(s"Hello sum: ${x}")
    }
}
